micronaut:
  application:
    name: gateway-api
  server:
    port: ${SERVER_PORT:9999}

netty:
  default:
    allocator:
      max-order: 3

consul:
  client:
    defaultZone: ${CONSUL_DEFAULT_ZONE:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: ${CONSUL_ENABLED:true}

gateway:
  services:
    - veiculo-service
    - loja-service
    - relatorio-service